version: '3'
services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: ${PGRST_DB_URI}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: ${API_URL}
  migrate:
    build:
      context: ./migrate
    container_name: migrate
    links:
      - db:db
    volumes:
      - "./migrate:/migrate"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
  app:
    build:
      context: ./app
    container_name: app
    volumes:
      - "./app:/app"
      - "/node_modules"
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      APP_PATH: ${APP_PATH}
      NODE_ENV: ${NODE_ENV}
    links:
      - postgrest:postgrest
    depends_on:
      - postgrest
    tty: true
