version: '3'
services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
  migrate:
    build:
      context: ./migrate
    container_name: migrate
    links:
      - db:db
    volumes:
      - "./migrate:/migrate"
    env_file:
      - .migrate.env
    depends_on:
      - db
  app:
    build:
      context: ./app
    container_name: app
    volumes:
      - "./app:/app"
      - "/node_modules"
    ports:
      - "3001:3000"
    env_file: 
      - .app.env
    links:
      - postgrest:postgrest
    depends_on:
      - postgrest
    tty: true
