ALTER TABLE question ADD COLUMN IF NOT EXISTS question_no SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE quiz_round ALTER COLUMN round_no SET DEFAULT 1;
ALTER TABLE quiz_round ALTER COLUMN round_no SET NOT NULL;
